
# Title : Heaps and AVL Trees
# Author : Yusuf Samsum
# Description : A simple AVL Tree and its rotation analysis

AVLTree:
	g++ -c AVLTreeNode.cpp AVLTree.cpp analysis.cpp main.cpp
	g++ AVLTreeNode.cpp AVLTree.cpp analysis.cpp main.cpp -o hw3
