# Title : Heaps and AVL Trees
# Author : Yusuf Samsum
# Description : A simple Max Heap and its analysis by using permutations and number of swaps.

MaxHeap:
	g++ -c MaxHeap.cpp main.cpp
	g++ MaxHeap.cpp main.cpp -o hw3